<?php

namespace Ulysse\Business\PurchaseBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
* MessageRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class RatingRepository extends EntityRepository
{

    public function findRatingBySale($sale)
    {
        $query = $this->_em
            ->createQueryBuilder()
            ->addSelect('r')
            ->from('UlysseBusinessPurchaseBundle:Rating', 'r')
            ->innerJoin('UlysseBusinessPurchaseBundle:Salepurchase', 's')
            ->where('s.sale = :sale')
            ->setParameter('sale', $sale)
            ->getQuery();

        return $query->getResult();
    }

}